# Generated by Django 5.2.4 on 2025-10-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_full_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('admission_class', models.CharField(max_length=50)),
                ('present_school', models.CharField(max_length=100)),
                ('board', models.CharField(choices=[('CISCE', 'CISCE'), ('CBSE', 'CBSE'), ('State Board', 'State Board')], max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=250)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
