# Generated by Django 5.2.4 on 2025-11-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_album_options_album_is_active_album_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/covers/'),
        ),
    ]
